# Generated by Django 6.0.6 on 2026-06-26 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mol_id', models.CharField(blank=True, max_length=100, null=True)),
                ('smiles', models.TextField()),
                ('canonical_smiles', models.TextField(unique=True)),
                ('nr_er', models.IntegerField(blank=True, null=True)),
                ('sr_p53', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('total_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('input_smiles', models.TextField()),
                ('canonical_smiles', models.TextField(blank=True, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('nr_er_source', models.CharField(default='-', max_length=20)),
                ('nr_er_result', models.IntegerField(blank=True, null=True)),
                ('nr_er_prob', models.FloatField(blank=True, null=True)),
                ('nr_er_threshold', models.FloatField(blank=True, null=True)),
                ('nr_er_risk', models.CharField(default='-', max_length=20)),
                ('sr_p53_source', models.CharField(default='-', max_length=20)),
                ('sr_p53_result', models.IntegerField(blank=True, null=True)),
                ('sr_p53_prob', models.FloatField(blank=True, null=True)),
                ('sr_p53_threshold', models.FloatField(blank=True, null=True)),
                ('sr_p53_risk', models.CharField(default='-', max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='predictor.analysisjob')),
            ],
            options={
                'ordering': ['row_number'],
            },
        ),
    ]
