# Generated by Django 6.0.6 on 2026-06-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_analysisresult_input_name_analysisresult_input_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='resolved_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
