# Generated by Django 6.0.6 on 2026-06-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_analysisresult_resolved_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='molecule',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='molecule',
            name='canonical_smiles',
            field=models.TextField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='molecule',
            name='nr_er',
            field=models.IntegerField(blank=True, null=True, verbose_name='NR-ER'),
        ),
        migrations.AlterField(
            model_name='molecule',
            name='sr_p53',
            field=models.IntegerField(blank=True, null=True, verbose_name='SR-p53'),
        ),
    ]
