# Generated by Django 6.0.6 on 2026-06-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0004_molecule_name_alter_molecule_canonical_smiles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='molecule',
            name='nr_er',
            field=models.IntegerField(blank=True, choices=[(0, '0 - 비활성 / 저위험'), (1, '1 - 활성 / 고위험')], null=True, verbose_name='NR-ER'),
        ),
        migrations.AlterField(
            model_name='molecule',
            name='sr_p53',
            field=models.IntegerField(blank=True, choices=[(0, '0 - 비활성 / 저위험'), (1, '1 - 활성 / 고위험')], null=True, verbose_name='SR-p53'),
        ),
    ]
