# Generated by Django 6.0.6 on 2026-06-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoleculeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_smiles', models.CharField(db_index=True, max_length=500, unique=True)),
                ('compound_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('nr_er_true', models.IntegerField(blank=True, null=True)),
                ('sr_p53_true', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'molecule_master',
            },
        ),
    ]
