# Generated by Django 6.0.6 on 2026-06-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name(화학물질명)')),
                ('smiles', models.TextField(verbose_name='SMILES')),
                ('nr_er', models.CharField(blank=True, max_length=20, verbose_name='NR-ER')),
                ('sr_p53', models.CharField(blank=True, max_length=20, verbose_name='SR-p53')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
            options={
                'verbose_name': '화학물질',
                'verbose_name_plural': '화학물질',
            },
        ),
    ]
