# Generated by Django 6.0.6 on 2026-06-29 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_chemicals', '0001_initial'),
        ('predictor', '0005_alter_molecule_nr_er_alter_molecule_sr_p53'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tox21Chemical',
            fields=[
            ],
            options={
                'verbose_name': '화학물질',
                'verbose_name_plural': '화학물질',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('predictor.molecule',),
        ),
    ]
