"""
Django settings for molecule project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-local-dev-key"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = "RENDER" not in os.environ

ALLOWED_HOSTS = ["*"] # 모든 IP허용


RENDER_EXTERNAL_HOSTNAME = os.environ.get("RENDER_EXTERNAL_HOSTNAME")

if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Application definition

INSTALLED_APPS = [ # 어플리케이션 추가시 여기!!!!!!!
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "accounts",
    "chemicals",
    
    "predictor", # predictor 추가
    
    "editor",
    
    "chem_analysis",
    "prediction",
    
    "admin_chemicals",
    "admin_prediction",
    "admin_csvmanager",
    "notice",
]
    


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "molecule.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"], # 여기도 수정!!!!!!!
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "molecule.context_processors.dashboard_counts",
            ],
        },
    },
]

WSGI_APPLICATION = "molecule.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "ko-kr"

TIME_ZONE = "Asia/Seoul"

USE_I18N = True

USE_TZ = True

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/accounts/login/"

JAZZMIN_SETTINGS = {

    "site_title": "TOX21", 
    "site_header": "TOX21",
    "site_brand": "Toxicity Platform",
    # "site_logo": "img/mainlogo1.png", #로그인페이지 이미지

    "welcome_sign": "Welcome TOX21  Admin",

    "show_sidebar": True,
    "navigation_expanded": True,

    "custom_css": "css/admin.css",

# ==========================================================
# 사이드 메뉴 아이콘
# ==========================================================

"icons": {

    # Dashboard
    "auth": "fas fa-users",

    # 화학물질
    "chemicals.Chemical": "fas fa-flask",

    # CSV
    "csvmanager.CSVUpload": "fas fa-file-csv",

    # ML 예측
    "prediction.Prediction": "fas fa-robot",

    # 공지사항
    "notice.Notice": "fas fa-bullhorn",

    # 사용자
    "auth.User": "fas fa-user",

    # 그룹
    "auth.Group": "fas fa-users-cog",

    },

    # ==========================================================
    # 메뉴 순서
    # ==========================================================
    "order_with_respect_to": [
    "chemicals",
    "csvmanager",
    "prediction",
    "notice",
    "auth",
    ],

    "changeform_format": "horizontal_tabs",
    "related_modal_active": True,
}
