# Generated by Django 6.0.6 on 2026-06-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_adminactionlog_loginhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="password_reset_required",
            field=models.BooleanField(
                default=False, verbose_name="비밀번호 초기화 여부"
            ),
        ),
    ]
