# Generated by Django 6.0.6 on 2026-06-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='csv/', verbose_name='CSV 파일')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드일')),
            ],
            options={
                'verbose_name': 'CSV 업로드',
                'verbose_name_plural': 'CSV 업로드',
            },
        ),
    ]
