# Generated by Django 6.0.6 on 2026-06-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chemical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="화학물질명")),
                ("formula", models.CharField(max_length=100, verbose_name="화학식")),
                ("smiles", models.TextField(blank=True, verbose_name="SMILES")),
                (
                    "toxicity",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="독성 결과"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
                ),
            ],
        ),
    ]
