# Generated by Django 6.0.6 on 2026-06-26 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chemicals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChemicalCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="카테고리명")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
            ],
        ),
        migrations.CreateModel(
            name="ChemicalNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="뉴스 제목")),
                (
                    "source",
                    models.CharField(blank=True, max_length=100, verbose_name="출처"),
                ),
                ("link", models.URLField(blank=True, verbose_name="뉴스 링크")),
                ("image_url", models.URLField(blank=True, verbose_name="이미지 URL")),
                (
                    "is_visible",
                    models.BooleanField(default=True, verbose_name="노출 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DatasetVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_name",
                    models.CharField(max_length=100, verbose_name="버전명"),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="현재 사용 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=200, verbose_name="질문")),
                ("answer", models.TextField(verbose_name="답변")),
                ("order", models.IntegerField(default=0, verbose_name="순서")),
                (
                    "is_visible",
                    models.BooleanField(default=True, verbose_name="노출 여부"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="이름")),
                ("email", models.EmailField(max_length=254, verbose_name="이메일")),
                ("title", models.CharField(max_length=200, verbose_name="문의 제목")),
                ("content", models.TextField(verbose_name="문의 내용")),
                ("answer", models.TextField(blank=True, verbose_name="답변")),
                (
                    "is_answered",
                    models.BooleanField(default=False, verbose_name="답변 완료"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="문의일"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MainBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="배너 제목")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="배너 부제목"
                    ),
                ),
                (
                    "image_url",
                    models.URLField(blank=True, verbose_name="배너 이미지 URL"),
                ),
                ("link", models.URLField(blank=True, verbose_name="연결 링크")),
                ("order", models.IntegerField(default=0, verbose_name="순서")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="사용 여부"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ToxicityEndpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Endpoint명")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="사용 여부"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="chemical",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="chemicals.chemicalcategory",
                verbose_name="카테고리",
            ),
        ),
        migrations.CreateModel(
            name="CSVUploadHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=200, verbose_name="파일명")),
                (
                    "total_count",
                    models.IntegerField(default=0, verbose_name="전체 데이터 수"),
                ),
                (
                    "success_count",
                    models.IntegerField(default=0, verbose_name="성공 수"),
                ),
                ("fail_count", models.IntegerField(default=0, verbose_name="실패 수")),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="업로드일"),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="업로드 관리자",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="공지 제목")),
                ("content", models.TextField(verbose_name="공지 내용")),
                (
                    "is_visible",
                    models.BooleanField(default=True, verbose_name="노출 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "writer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PredictionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("smiles", models.TextField(verbose_name="SMILES")),
                (
                    "prediction_result",
                    models.CharField(max_length=100, verbose_name="예측 결과"),
                ),
                ("probability", models.FloatField(default=0, verbose_name="예측 확률")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="예측 시간"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
                (
                    "endpoint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="chemicals.toxicityendpoint",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="chemical",
            name="endpoint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="chemicals.toxicityendpoint",
                verbose_name="Endpoint",
            ),
        ),
    ]
